#include "/Engine/Private/Common.ush"
int numOctaves;
float noiseStrength;
float scale;

//Roughness ofgenerated terrain
float persistence;

//Controls Detail between octaves
float lacunarity;

//Controls zoom of noise pattern
float baseFrequency;    

Buffer<float> inputVertices;
RWBuffer<float> outputVertices;

// Gets random values
float hash(float n)
{
    return frac(sin(n) * 43758.5453);
}

//Found this online
float noise3D(float3 x)
{
    float3 p = floor(x);
    float3 f = frac(x);
    
    f = f * f * (3.0 - 2.0 * f);
    
    float n = p.x + p.y * 57.0 + 113.0 * p.z;
    
    return lerp(
        lerp(
            lerp(hash(n + 0.0), hash(n + 1.0), f.x),
            lerp(hash(n + 57.0), hash(n + 58.0), f.x), f.y),
        lerp(
            lerp(hash(n + 113.0), hash(n + 114.0), f.x),
            lerp(hash(n + 170.0), hash(n + 171.0), f.x), f.y), f.z);
}

//My CPU code
float fractalNoise(float3 p)
{
    float totalNoise = 0.0;
    float amplitude = 1.0;
    float frequency = baseFrequency;
    
    for (int octave = 0; octave < numOctaves; ++octave)
    {
        totalNoise += noise3D(p * frequency) * amplitude;
        amplitude *= persistence;
        frequency *= lacunarity;
    }
    
    return totalNoise * 2.0 - 1.0; 
}

[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void NoiseShader(uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    
    //First element of input is vertex num
    uint vertexCount = (uint) inputVertices[0];
    
    if (index >= vertexCount)
        return;
    
    //Data conversion
    uint dataIndex = index * 3 + 1;
    float3 vertex = float3(
        inputVertices[dataIndex],
        inputVertices[dataIndex + 1],
        inputVertices[dataIndex + 2]
    );
    
    float3 normalizedPos = normalize(vertex);
    float totalNoise = fractalNoise(normalizedPos);
    float3 displacedVertex = vertex + normalizedPos * totalNoise * noiseStrength * 10.0;
    
    //Output
    uint outputIndex = index * 3;
    outputVertices[outputIndex] = displacedVertex.x;
    outputVertices[outputIndex + 1] = displacedVertex.y;
    outputVertices[outputIndex + 2] = displacedVertex.z;
}